version: "2"

services:
  broker:
    image: philipz/mosquitto
    ports:
      - "1883:1883"

  Sub:
    container_name: sub
    image: philipz/rpi-raspbian-mqtt
    environment:
      - QEMU_EXECVE=1
    volumes:
      - $(pwd)/qemu/qemu-arm-static:/usr/bin/qemu-arm-static
      - $(pwd)/qemu/sh-shim:/usr/bin/sh-shim
      - $(pwd)/qemu/cross-build-start:/usr/bin/cross-build-start
    command: cross-build-start && mosquitto_sub -h localhost -t /test
