version: "2"

services:
  broker:
    image: philipz/mosquitto
    ports:
      - "1883:1883"

  Sub:
    container_name: sub
    image: philipz/rpi-raspbian-mqtt
    environment:
      - QEMU_EXECVE=1
    volumes:
      - ./qemu/qemu-arm-static:/usr/bin/qemu-arm-static
      - ./qemu/sh-shim:/usr/bin/sh-shim
      - ./qemu/cross-build-start:/usr/bin/cross-build-start
    command: mosquitto_sub -h localhost -t /test
