version: "2"

services:
  broker:
    image: philipz/mosquitto
    ports:
      - "1883:1883"

  Sub:
    depends_on:
      - broker
    container_name: sub
    image: philipz/rpi-raspbian-mqtt
    command: qemu-arm-static /bin/sh -c 'mosquitto_sub -h localhost -t /test'

  Pub:
    depends_on:
      - Sub
    container_name: pub
    image: philipz/rpi-raspbian-mqtt
    command: qemu-arm-static /bin/sh -c 'mosquitto_pub -h localhost -t /test -m Hello_World,Philipz!'
